[package]
name = "human"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde"]

[dependencies]
serde = { version = "1.0.210", features = ["derive"], optional = true }

[dev-dependencies]
arbitrary = { version = "1.3.2", features = ["derive", "derive_arbitrary"] }
arbtest = "0.3.1"
