---
name: CI
on: [push]
env:
  RUST_BACKTRACE: 1
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Init
        run: ./ci/init.sh
      - name: Lint
        run: ./ci/lint.sh
      - name: Test
        run: ./ci/test.sh
      - name: Benchmarks
        run: ./ci/bench.sh
  msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Install cargo-msrv
        run: cargo install --quiet cargo-msrv
      - name: Check MSRV
        run: cargo msrv --workspace verify
  publish:
    needs: [tests, msrv]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: ./ci/publish.sh
