---
name: CI
on: [pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref
    }}
  cancel-in-progress: true
env:
  RUST_BACKTRACE: 1
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Init
        run: ./ci/init.sh
      - name: Lint
        run: ./ci/lint.sh
      - name: Test
        run: ./ci/test.sh
      - name: Benchmarks
        run: ./ci/bench.sh
  msrv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.4
      - name: Install cargo-msrv
        run: cargo install --quiet cargo-msrv
      - name: Check MSRV
        run: cargo msrv --workspace verify
